### ISSUE TITLE
Sliding when standing still on a slope

### ISSUE THREAD

**Issue by TiliSleepStealer** [Moe-Baker/Advanced-Rigidbody-FirstPerson-Controller#1]
My character is sliding when standing on a slope without any input.
The slope angle is lower than the max slop angle.
Any ideas on how to fix that?

**Comment by TiliSleepStealer** [comment]
I think this fixes it:

![image](https://user-images.githubusercontent.com/6567869/34998961-56aed75c-fad8-11e7-98b9-19e7802104d2.png)

**Comment by Moe-Baker** [comment]
Yes this is a bit of a problem, I wanted to do a more complex solution in the future by manually simulating gravity based on slope angle, but this is pretty sufficient, will do this till i get to the other solution, thanks for the hotfix

**Comment by dknight3** [comment]
Thanks for the fix!
